### ISSUE TITLE
Data Value Permissions

### ISSUE THREAD

**Issue by williamhatcher** [Zerthick/ProtectionPerms#12]
I know you can specify blockstates, but what about data values?

I want to allow (or disallow) players to use bonemeal, but not dye sheep.

**Comment by Zerthick** [comment]
So I can implement this, but it'll be something really ugly like `protectionperms.item.use.{"ContentVersion":1,"ItemType":"minecraft:dye","Count":1,"UnsafeDamage":15}` I'm trying to see if I can come up with a better way to do this, in Minecraft 1.13 this issue should be resolved by them actually adding in separate ids for everything
