### ISSUE TITLE
Dropping Items Causes Item to Disappear from Inventory

### ISSUE THREAD

**Issue by williamhatcher** [Zerthick/ProtectionPerms#13]
With dropping of items prevented, when a player tries to drop an item, the item is removed from their inventory and destroyed.

**Comment by Zerthick** [comment]
Yes I'm aware, this is a bug in sponge unfortunately. I've created an issue for it here: https://github.com/SpongePowered/SpongeCommon/issues/1678 where you can track it's progress

**Comment by Zerthick** [comment]
So this is still unfixable due to another sponge bug: https://github.com/SpongePowered/SpongeCommon/issues/2044
