### ISSUE TITLE
Documentation Should be Moved to Wiki

### ISSUE THREAD

**Issue by williamhatcher** [Zerthick/ProtectionPerms#15]
The README is getting rather lengthy. I'd like to help you build a wiki to break everything up, and document it better.

What do you think?

**Comment by Zerthick** [comment]
If you'd like to take a stab at it, sure!

**Comment by williamhatcher** [comment]
I don't have access to edit the wiki. You'd either have to make me a collaborator on this repo, or allow me to edit the wiki. See [Changing access permissions for wikis](https://help.github.com/articles/changing-access-permissions-for-wikis/).

If you were to put me as a collaborator, I would be able to push edits to the README.md without having to create multiple PRs

**Comment by Zerthick** [comment]
You should be able to edit the wiki now

**Comment by williamhatcher** [comment]
[Permissions](https://github.com/Zerthick/ProtectionPerms/wiki/Permissions) have been documented.

**Comment by williamhatcher** [comment]
[Configuration](https://github.com/Zerthick/ProtectionPerms/wiki/Configuration) page added.
