### ISSUE TITLE
Question item craft

### ISSUE THREAD

**Issue by crymates** [Zerthick/ProtectionPerms#3]
Can I deny crafting items using this plugin?

Greetz,
Hannes

**Comment by crymates** [comment]
I tried to deny crafting an iron axe with `protectionperms.item.craft.minecraft:iron_axe` but it doesn't work.
Pls pls add this feature! ;)

**Comment by crymates** [comment]
`protectionperms.item.crafting.minecraft:iron_axe` also does not work.

**Comment by Zerthick** [comment]
Unfortunately due to limitations with Sponge I've been unable to restrict crafting as of yet, however I definitely intend to add this feature once the Sponge API allows me :smile:

**Comment by Zerthick** [comment]
Added in [v0.6.0](https://github.com/Zerthick/ProtectionPerms/releases/tag/v0.6.0)!
