### ISSUE TITLE
Craft Item

### ISSUE THREAD

**Issue by comdarksider** [Zerthick/ProtectionPerms#5]
Please make separate plugins for control item craft only because I need easy to use and I open server for pixelmon mod.

**Comment by Zerthick** [comment]
You have this type of functionality with protection perms as is so long as your permissions plugin supports something like a wildcard just give all your players permission to `protectionperms.block.*`, `protectionperms.entity.*`, `protectionperms.item.use.*`, and `protectionperms.item.drop.*`. Then only give your players the crafting permissions you want. 😄
