### ISSUE TITLE
Question: Item / Block Varient in MC 1.10.2

### ISSUE THREAD

**Issue by mister-man** [Zerthick/ProtectionPerms#7]
Hallo together,

is there any chance to use "[variant=andesite]" in mc 1.10.2? I saw an imülementation in the newer version for 1.11... but most other client mods are not avalible for newer Versions like mc 1.10.2.

Thanks!

**Comment by Zerthick** [comment]
Yep, shouldn't be too hard to do a backport to 1.10.2, you can expect a release shortly 😄

**Comment by mister-man** [comment]
Thanks a lot :)

**Comment by Zerthick** [comment]
Sorry for the delay, here's the backport to 1.10.2: https://github.com/Zerthick/ProtectionPerms/releases/tag/v1.0.1 :smiley:

**Comment by mister-man** [comment]
Thanks a lot. It makes my server idea possible :)

**Comment by mister-man** [comment]
Hallo Zerthick,

maybe I found an error. I tried to allow my testuser to braek a block of oakwood. But it only works if the testuser has the variant and the non variant permission.

`
"protectionperms.block.break.minecraft:log": 1,
"protectionperms.block.break.minecraft:log[axis=y,variant=oak]": 1,
`

Here the debug output of pex:

`
<21:14:21> "Snipped": [21:12:41] [Server thread/INFO] [permissionsex]: Permission protectionperms.block.break.minecraft:log checked in [world=world, localport=25565, localip=192.168.178.22, localhost=192.168.178.22, dimension=minecraft.overworld, remoteip=192.168.178.22] for user xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx: 1
[21:12:41] [Server thread/INFO] [permissionsex]: Permission protectionperms.block.break.minecraft:log[axis=y,variant=oak] checked in [world=world, localport=25565, localip=192.168.178.22, localhost=192.168.178.22, dimension=minecraft.overworld, remoteip=192.168.178.22] for user xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx: 1
`

If one of the debug outputs 0, my testuser can't break oakwood.

**Comment by Zerthick** [comment]
Looking into this

**Comment by Snipped** [comment]
Hello Zerthick,
if I see it right, you have adjusted the listeners for blocks a few days ago. It seems that the same problem exists with the listeners in the item folder.
https://github.com/Zerthick/ProtectionPerms/tree/master/src/main/java/io/github/zerthick/protectionperms/events/listeners

**Comment by Zerthick** [comment]
Oops, you're right, time for a new patch!

**Comment by Zerthick** [comment]
@Snipped Should be fixed in [v1.0.3](https://github.com/Zerthick/ProtectionPerms/releases/tag/v1.0.3)!
